# Generated by Django 3.2.4 on 2021-06-24 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic_name', models.CharField(max_length=50)),
                ('clinic_email', models.EmailField(max_length=254)),
                ('clinic_phone', models.IntegerField(max_length=8)),
                ('clinic_area', models.CharField(max_length=50)),
                ('clinic_address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('patient_email', models.EmailField(max_length=254)),
                ('patient_phone', models.IntegerField(max_length=8)),
                ('patient_area', models.CharField(max_length=50)),
                ('patient_address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(max_length=50)),
                ('service_price', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField()),
                ('payment_status', models.IntegerField(choices=[(0, 'Unpaid'), (1, 'Paid'), (2, 'Failed')], default=0)),
                ('payment_method', models.IntegerField(choices=[(0, 'Card'), (1, 'Cash')], default=0)),
                ('patient_pay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.patient')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.service')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=50)),
                ('majoring', models.CharField(max_length=50)),
                ('clinic_email', models.EmailField(max_length=254)),
                ('clinic_phone', models.IntegerField(max_length=8)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.clinic')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateTimeField(auto_now_add=True)),
                ('appointment_status', models.IntegerField(choices=[(0, 'Schedule'), (1, 'Confirmed'), (2, 'Cancelled')], default=0)),
                ('clinic_ap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.clinic')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.patient')),
            ],
        ),
    ]
