# Generated by Django 3.2.4 on 2021-06-25 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210625_1737'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clinic',
            old_name='clinic_address',
            new_name='clinic_location',
        ),
    ]
